service:
  name: scrapbox-lambda

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  getArts:
    handler: handler.getArts
    events:
      - http:
          method: get
          path: arts
